version: '2'
services:
    blank-app:
        image: blank
        environment:
            - SPRING_PROFILES_ACTIVE=prod,swagger
            - SPRING_DATASOURCE_URL=jdbc:oracle:thin:@blank-oracle:1521:blank
            - JHIPSTER_SLEEP=10 # gives time for the database to boot before the application
        ports:
            - 7070:7070
